name: Ensure_Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Build Linux and Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        compiler:
          - llvm
          - gcc

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          cppcheck: true

      - name: Move to Build Folder
        run: cd build

      - name: Generate Build Files
        run: cmake ..

      - name: Move to root folder
        run: cd ..

      - name: Test CMake Build
        run: cmake build

