name: Ensure_Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Build Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        compiler:
          - llvm
          - gcc

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          cppcheck: true
