name: Ensure_Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Build Linux and Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        compiler:
          - llvm
          - gcc

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          conan: true
          cmake: true
          ninja: true
          cppcheck: true

      - name: Create Conan Profile
        run: conan profile detect --force

      - name: Install Conan Packages
        run: conan install .

      - name: Test CMake Build
        run: cmake -B build -S .

